/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DienstenRouteImport } from './routes/diensten'
import { Route as HoeWeWerkenRouteImport } from './routes/hoe-we-werken'
import { Route as OverLoopwerkRouteImport } from './routes/over-loopwerk'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as WerkwijzeRouteImport } from './routes/werkwijze'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesSspwZwembadconfiguratorRouteImport } from './routes/cases.sspw-zwembadconfigurator'
import { Route as OplossingenIndexRouteImport } from './routes/oplossingen.index'
import { Route as OplossingenSlugRouteImport } from './routes/oplossingen.$slug'
import { Route as SectorenIndexRouteImport } from './routes/sectoren.index'
import { Route as SectorenSlugRouteImport } from './routes/sectoren.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenRoute = DienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => rootRouteImport,
} as any)
const HoeWeWerkenRoute = HoeWeWerkenRouteImport.update({
  id: '/hoe-we-werken',
  path: '/hoe-we-werken',
  getParentRoute: () => rootRouteImport,
} as any)
const OverLoopwerkRoute = OverLoopwerkRouteImport.update({
  id: '/over-loopwerk',
  path: '/over-loopwerk',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const WerkwijzeRoute = WerkwijzeRouteImport.update({
  id: '/werkwijze',
  path: '/werkwijze',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesSspwZwembadconfiguratorRoute =
  CasesSspwZwembadconfiguratorRouteImport.update({
    id: '/cases/sspw-zwembadconfigurator',
    path: '/cases/sspw-zwembadconfigurator',
    getParentRoute: () => rootRouteImport,
  } as any)
const OplossingenIndexRoute = OplossingenIndexRouteImport.update({
  id: '/oplossingen/',
  path: '/oplossingen/',
  getParentRoute: () => rootRouteImport,
} as any)
const OplossingenSlugRoute = OplossingenSlugRouteImport.update({
  id: '/oplossingen/$slug',
  path: '/oplossingen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorenIndexRoute = SectorenIndexRouteImport.update({
  id: '/sectoren/',
  path: '/sectoren/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorenSlugRoute = SectorenSlugRouteImport.update({
  id: '/sectoren/$slug',
  path: '/sectoren/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/hoe-we-werken': typeof HoeWeWerkenRoute
  '/over-loopwerk': typeof OverLoopwerkRoute
  '/over-ons': typeof OverOnsRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/cases/sspw-zwembadconfigurator': typeof CasesSspwZwembadconfiguratorRoute
  '/oplossingen/$slug': typeof OplossingenSlugRoute
  '/sectoren/$slug': typeof SectorenSlugRoute
  '/cases/': typeof CasesIndexRoute
  '/oplossingen/': typeof OplossingenIndexRoute
  '/sectoren/': typeof SectorenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/hoe-we-werken': typeof HoeWeWerkenRoute
  '/over-loopwerk': typeof OverLoopwerkRoute
  '/over-ons': typeof OverOnsRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/cases/sspw-zwembadconfigurator': typeof CasesSspwZwembadconfiguratorRoute
  '/oplossingen/$slug': typeof OplossingenSlugRoute
  '/sectoren/$slug': typeof SectorenSlugRoute
  '/cases': typeof CasesIndexRoute
  '/oplossingen': typeof OplossingenIndexRoute
  '/sectoren': typeof SectorenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/hoe-we-werken': typeof HoeWeWerkenRoute
  '/over-loopwerk': typeof OverLoopwerkRoute
  '/over-ons': typeof OverOnsRoute
  '/werkwijze': typeof WerkwijzeRoute
  '/cases/sspw-zwembadconfigurator': typeof CasesSspwZwembadconfiguratorRoute
  '/oplossingen/$slug': typeof OplossingenSlugRoute
  '/sectoren/$slug': typeof SectorenSlugRoute
  '/cases/': typeof CasesIndexRoute
  '/oplossingen/': typeof OplossingenIndexRoute
  '/sectoren/': typeof SectorenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/diensten'
    | '/hoe-we-werken'
    | '/over-loopwerk'
    | '/over-ons'
    | '/werkwijze'
    | '/cases/sspw-zwembadconfigurator'
    | '/oplossingen/$slug'
    | '/sectoren/$slug'
    | '/cases/'
    | '/oplossingen/'
    | '/sectoren/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/diensten'
    | '/hoe-we-werken'
    | '/over-loopwerk'
    | '/over-ons'
    | '/werkwijze'
    | '/cases/sspw-zwembadconfigurator'
    | '/oplossingen/$slug'
    | '/sectoren/$slug'
    | '/cases'
    | '/oplossingen'
    | '/sectoren'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/diensten'
    | '/hoe-we-werken'
    | '/over-loopwerk'
    | '/over-ons'
    | '/werkwijze'
    | '/cases/sspw-zwembadconfigurator'
    | '/oplossingen/$slug'
    | '/sectoren/$slug'
    | '/cases/'
    | '/oplossingen/'
    | '/sectoren/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DienstenRoute: typeof DienstenRoute
  HoeWeWerkenRoute: typeof HoeWeWerkenRoute
  OverLoopwerkRoute: typeof OverLoopwerkRoute
  OverOnsRoute: typeof OverOnsRoute
  WerkwijzeRoute: typeof WerkwijzeRoute
  CasesSspwZwembadconfiguratorRoute: typeof CasesSspwZwembadconfiguratorRoute
  OplossingenSlugRoute: typeof OplossingenSlugRoute
  SectorenSlugRoute: typeof SectorenSlugRoute
  CasesIndexRoute: typeof CasesIndexRoute
  OplossingenIndexRoute: typeof OplossingenIndexRoute
  SectorenIndexRoute: typeof SectorenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten': {
      id: '/diensten'
      path: '/diensten'
      fullPath: '/diensten'
      preLoaderRoute: typeof DienstenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoe-we-werken': {
      id: '/hoe-we-werken'
      path: '/hoe-we-werken'
      fullPath: '/hoe-we-werken'
      preLoaderRoute: typeof HoeWeWerkenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-loopwerk': {
      id: '/over-loopwerk'
      path: '/over-loopwerk'
      fullPath: '/over-loopwerk'
      preLoaderRoute: typeof OverLoopwerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/werkwijze': {
      id: '/werkwijze'
      path: '/werkwijze'
      fullPath: '/werkwijze'
      preLoaderRoute: typeof WerkwijzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/sspw-zwembadconfigurator': {
      id: '/cases/sspw-zwembadconfigurator'
      path: '/cases/sspw-zwembadconfigurator'
      fullPath: '/cases/sspw-zwembadconfigurator'
      preLoaderRoute: typeof CasesSspwZwembadconfiguratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oplossingen/': {
      id: '/oplossingen/'
      path: '/oplossingen'
      fullPath: '/oplossingen/'
      preLoaderRoute: typeof OplossingenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oplossingen/$slug': {
      id: '/oplossingen/$slug'
      path: '/oplossingen/$slug'
      fullPath: '/oplossingen/$slug'
      preLoaderRoute: typeof OplossingenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectoren/': {
      id: '/sectoren/'
      path: '/sectoren'
      fullPath: '/sectoren/'
      preLoaderRoute: typeof SectorenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectoren/$slug': {
      id: '/sectoren/$slug'
      path: '/sectoren/$slug'
      fullPath: '/sectoren/$slug'
      preLoaderRoute: typeof SectorenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DienstenRoute: DienstenRoute,
  HoeWeWerkenRoute: HoeWeWerkenRoute,
  OverLoopwerkRoute: OverLoopwerkRoute,
  OverOnsRoute: OverOnsRoute,
  WerkwijzeRoute: WerkwijzeRoute,
  CasesSspwZwembadconfiguratorRoute: CasesSspwZwembadconfiguratorRoute,
  OplossingenSlugRoute: OplossingenSlugRoute,
  SectorenSlugRoute: SectorenSlugRoute,
  CasesIndexRoute: CasesIndexRoute,
  OplossingenIndexRoute: OplossingenIndexRoute,
  SectorenIndexRoute: SectorenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
