/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DienstenRouteImport } from './routes/diensten'
import { Route as WerkwijzeRouteImport } from './routes/werkwijze'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenRoute = DienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => rootRouteImport,
} as any)
const WerkwijzeRoute = WerkwijzeRouteImport.update({
  id: '/werkwijze',
  path: '/werkwijze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diensten': typeof DienstenRoute
  '/werkwijze': typeof WerkwijzeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diensten': typeof DienstenRoute
  '/werkwijze': typeof WerkwijzeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diensten': typeof DienstenRoute
  '/werkwijze': typeof WerkwijzeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diensten' | '/werkwijze'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diensten' | '/werkwijze'
  id: '__root__' | '/' | '/diensten' | '/werkwijze'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DienstenRoute: typeof DienstenRoute
  WerkwijzeRoute: typeof WerkwijzeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten': {
      id: '/diensten'
      path: '/diensten'
      fullPath: '/diensten'
      preLoaderRoute: typeof DienstenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/werkwijze': {
      id: '/werkwijze'
      path: '/werkwijze'
      fullPath: '/werkwijze'
      preLoaderRoute: typeof WerkwijzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DienstenRoute: DienstenRoute,
  WerkwijzeRoute: WerkwijzeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
